# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default

steps:
- script: python3 /home/azureuser/dnstwist/dns_check.py

schedules:
- cron: '01 */6 * * *'
  displayName: Weekly Sunday build
  branches:
    include:
    - main
  always: true